"""
ild_pdf — auskoppelbares PDF-Modul für InstantLens Doc und andere Apps.

Basiert auf pypdfium2 (PDFium, lizenzfreundlich). Kein Poppler/GPL.
"""

from .document import PdfDocument, format_page_status
from .render import render_page, render_pages
from .annotate import (
    Annotation,
    AnnotationImportError,
    AnnotationStore,
    AnnotationType,
    DRAG_TYPES,
    FAV_SCHEMA_ID,
    FAV_VERSION,
    FavoritesImportError,
    SCHEMA_ID,
    SIDECAR_VERSION,
    normalize_tags,
    tags_to_str,
    validate_annotation_import_data,
    STAMP_LIBRARY,
    STAMP_PRESETS,
    stamp_library_items,
    stamp_with_date,
)
from .pages import (
    PAGE_SIZE_PRESETS,
    extract_page_range,
    extract_pages,
    extract_page_bytes,
    insert_page_from_bytes,
    merge_pdfs,
    split_into_single_page_pdfs,
    split_pdf,
    rotate_page,
    flip_page,
    insert_blank_page,
    duplicate_page,
    delete_pages,
    reorder_pages,
    format_size_pair,
    get_page_boxes,
    set_page_size,
    convert_pt,
    to_pt,
    pt_to_inch,
    pt_to_mm,
    mm_to_pt,
    inch_to_pt,
    set_crop_box,
)
from .flatten import bake_annotations, draw_annotations_on_image, flatten_annotations_to_pdf
from .outline import OutlineItem, add_outline_item, delete_outline_item, extract_outline
from .images import (
    compress_image_for_pdf,
    compress_pdf_as_images,
    extract_page_image,
    extract_pages_as_images,
    extract_embedded_images,
    insert_image_as_page,
    insert_image_stamp_overlay,
    insert_signature_field,
    insert_signature_image,
)
from .overlay import (
    SearchPatternError,
    TextBlock,
    TextMatchRect,
    bake_text_overlays,
    extract_all_plain_text,
    extract_page_plain_text,
    extract_text_blocks,
    find_text_rects,
    import_page_text_as_overlays,
    selection_to_highlight_rects,
    selection_to_plain_text,
)
from .watermark import apply_page_numbers, apply_watermark
from .limits import PdfHealth, clamp_render_scale, inspect_pdf
from .render import clear_render_cache
from .security import needs_password, remove_password, set_password, try_open_password
from .redact import bake_redactions
from .metadata import PdfMetadata, get_metadata, sanitize_pdf, set_metadata, strip_metadata
from .acroform import (
    FormFieldInfo,
    get_form_values,
    has_acroform,
    list_form_fields,
    set_form_values,
)
from .attachments import (
    AttachmentInfo,
    extract_all_attachments,
    extract_attachment,
    has_attachments,
    list_attachments,
)
from .links import UriLink, is_external_http_uri, list_page_uri_links, uri_link_at

__all__ = [
    "PdfDocument",
    "format_page_status",
    "render_page",
    "render_pages",
    "clear_render_cache",
    "Annotation",
    "AnnotationImportError",
    "AnnotationStore",
    "AnnotationType",
    "validate_annotation_import_data",
    "DRAG_TYPES",
    "FAV_SCHEMA_ID",
    "FAV_VERSION",
    "FavoritesImportError",
    "SCHEMA_ID",
    "SIDECAR_VERSION",
    "normalize_tags",
    "tags_to_str",
    "STAMP_PRESETS",
    "STAMP_LIBRARY",
    "stamp_with_date",
    "stamp_library_items",
    "PAGE_SIZE_PRESETS",
    "extract_page_range",
    "extract_pages",
    "merge_pdfs",
    "split_into_single_page_pdfs",
    "split_pdf",
    "flatten_annotations_to_pdf",
    "bake_annotations",
    "draw_annotations_on_image",
    "rotate_page",
    "flip_page",
    "insert_blank_page",
    "duplicate_page",
    "delete_pages",
    "extract_page_bytes",
    "insert_page_from_bytes",
    "reorder_pages",
    "get_page_boxes",
    "set_page_size",
    "set_crop_box",
    "format_size_pair",
    "convert_pt",
    "to_pt",
    "pt_to_mm",
    "pt_to_inch",
    "mm_to_pt",
    "inch_to_pt",
    "OutlineItem",
    "extract_outline",
    "add_outline_item",
    "delete_outline_item",
    "compress_image_for_pdf",
    "compress_pdf_as_images",
    "extract_page_image",
    "extract_pages_as_images",
    "extract_embedded_images",
    "insert_image_as_page",
    "insert_image_stamp_overlay",
    "insert_signature_field",
    "insert_signature_image",
    "SearchPatternError",
    "TextBlock",
    "TextMatchRect",
    "extract_text_blocks",
    "extract_page_plain_text",
    "extract_all_plain_text",
    "find_text_rects",
    "import_page_text_as_overlays",
    "selection_to_highlight_rects",
    "selection_to_plain_text",
    "bake_text_overlays",
    "apply_watermark",
    "apply_page_numbers",
    "PdfHealth",
    "inspect_pdf",
    "clamp_render_scale",
    "needs_password",
    "try_open_password",
    "set_password",
    "remove_password",
    "bake_redactions",
    "PdfMetadata",
    "get_metadata",
    "set_metadata",
    "strip_metadata",
    "sanitize_pdf",
    "FormFieldInfo",
    "has_acroform",
    "list_form_fields",
    "get_form_values",
    "set_form_values",
    "AttachmentInfo",
    "has_attachments",
    "list_attachments",
    "extract_attachment",
    "extract_all_attachments",
    "UriLink",
    "is_external_http_uri",
    "list_page_uri_links",
    "uri_link_at",
]

__version__ = "1.1.2"
